import { ReactNode } from 'react';
import { Inter } from 'next/font/google';

import type { Metadata } from 'next';

import Header from '@/app/components/Header';

import './globals.css';


const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'NextJs 13 Lab 1',
  description: 'Generated by create next app',
};

export default function RootLayout(
  { children }: { children: ReactNode }) {
  return (
    <html lang='en'>
    <body className={inter.className}>
    <Header />
    <main className='container'>{children}</main>
    </body>
    </html>
  );
}
